In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import cross_validation, neighbors


In [84]:
cars = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data")
print(cars.head())

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc


In [85]:
columns=["Buying","Maint","Door","Persons","Boot_lug","Safety","Result"]
cars.columns=columns
print(cars.head())

  Buying  Maint Door Persons Boot_lug Safety Result
0  vhigh  vhigh    2       2    small    med  unacc
1  vhigh  vhigh    2       2    small   high  unacc
2  vhigh  vhigh    2       2      med    low  unacc
3  vhigh  vhigh    2       2      med    med  unacc
4  vhigh  vhigh    2       2      med   high  unacc


In [0]:
#To Handle Non Numeric Data before fitting in classifier, we define a function to change the non numeric data into integers
def TextToNumber(df):
  columns=df.columns.values
  for column in columns:
    parseddata={}
    def ConvertToInt(value):
      return parseddata[value]
    if(df[column].dtype!=np.int64 and df[column].dtype!=np.float64):
      column_contents=df[column].values.tolist()
      unique_elements=set(column_contents)
      x=0
      for unique in unique_elements:
        if unique not in parseddata:
          parseddata[unique]=x
          x=x+1
      df[column]=list(map(ConvertToInt,df[column]))
  return df  
#Function Ends


In [87]:
y=np.array(cars['Result'])
X=np.array(TextToNumber(cars.drop(['Result'],1)))

print(X[:5])
print(y[:5])

[[0 0 0 0 2 0]
 [0 0 0 0 2 1]
 [0 0 0 0 1 2]
 [0 0 0 0 1 0]
 [0 0 0 0 1 1]]
['unacc' 'unacc' 'unacc' 'unacc' 'unacc']


In [88]:
X_train,X_test,Y_train,Y_test=cross_validation.train_test_split(X,y,test_size=0.2)
clf=neighbors.KNeighborsClassifier()

clf.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [89]:
predictdata=pd.concat([pd.Series(['vhigh']),pd.Series(['low']),pd.Series([2]),pd.Series(['more']),pd.Series(['med']),pd.Series(['low'])], axis=1)
print(predictdata)
predictdata=np.array(TextToNumber(predictdata))
print(predictdata)
predictdata.shape=(1,-1)
#print(predictdata)
prediction=clf.predict(predictdata)
print(prediction)

       0    1  2     3    4    5
0  vhigh  low  2  more  med  low
[[0 0 2 0 0 0]]
['unacc']
